name: DeployMoonbeam
on:
  push:
    branches:
      - moonbeam

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn
      - run: yarn add @graphprotocol/graph-cli
      - run: yarn add gluegun
      - run: yarn run codegen
      - run: graph auth --product hosted-service ${API_KEY}
        env:
          API_KEY: ${{ secrets.HP_GRAPH_API_KEY }}
      - run: graph deploy --product hosted-service humanprotocol/moonbeam