name: Ci
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      env:
        API_KEY: ${{ secrets.GRAPH_API_KEY }}
      - uses: actions/checkout@v3
      - name: Set up JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm install -g @graphprotocol/graph-cli
      - run: graph codegen
      - run: graph build
      - run: graph auth --product ${API_KEY}
